# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/tools/quickstartgen" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/quickstarts/101-hello-power-platform" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/quickstarts/102-github-pipeline" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/quickstarts/103-power-pipelines" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/quickstarts/201-D365-finance-environment" # Location of package manifests
    schedule:
      interval: "daily"      
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/quickstarts/300-pac-checkov" # Location of package manifests
    schedule:
      interval: "daily"    
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/bootstrap/tenant-configuration" # Location of package manifests
    schedule:
      interval: "daily"              
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/.github/workflows" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "devcontainers" # See documentation for possible values
    directory: "/"
    schedule:
      interval: "daily"
